version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "@elide-dev/engineering"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "@elide-dev/engineering"

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
