name = "elide-site"
main = "dist/server.workers.mjs"
workers_dev = false
compatibility_date = "2022-07-12"
compatibility_flags = ["streams_enable_constructors", "nodejs_compat"]

kv_namespaces = [
]

[site]
bucket = "./dist"
